# Generated by Django 2.1.2 on 2019-01-01 00:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('examen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='heure',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
