# Generated by Django 2.1.2 on 2018-12-31 15:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.TextField(max_length=45)),
                ('volume', models.IntegerField()),
            ],
            options={
                'verbose_name': 'cours',
                'ordering': ['volume'],
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finger', models.TextField(max_length=1000000)),
                ('nom', models.TextField(max_length=45)),
                ('post_nom', models.TextField(max_length=45)),
                ('pre_nom', models.TextField(max_length=45)),
            ],
            options={
                'verbose_name': 'enseignant',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finger', models.TextField(max_length=1000000)),
                ('nom', models.TextField(max_length=45)),
                ('post_nom', models.TextField(max_length=45)),
                ('pre_nom', models.TextField(max_length=45)),
                ('faculte', models.TextField(max_length=45)),
                ('promotion', models.TextField(max_length=45)),
                ('cours_suivis', models.ManyToManyField(to='cours.Cours')),
            ],
            options={
                'verbose_name': 'etudiant',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PresencesEt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField(default=django.utils.timezone.now)),
                ('debut', models.BooleanField(default=False)),
                ('fin', models.BooleanField(default=False)),
                ('pause', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.Etudiant')),
            ],
            options={
                'verbose_name': 'presencesEt',
                'ordering': ['jour'],
            },
        ),
        migrations.AddField(
            model_name='cours',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cours.Enseignant'),
        ),
    ]
