# Generated by Django 2.1.2 on 2018-12-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='faculte',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='post_nom',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='pre_nom',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='promotion',
            field=models.CharField(max_length=45),
        ),
    ]
