# Generated by Django 2.1.2 on 2018-12-31 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0002_auto_20181231_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cours',
            name='intitule',
            field=models.CharField(max_length=45),
        ),
    ]
