# Generated by Django 2.1.2 on 2019-01-01 00:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cours', '0003_auto_20181231_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='presenceset',
            name='heure',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
