# Generated by Django 2.1.2 on 2018-12-31 15:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finger', models.TextField(max_length=1000000)),
                ('nom', models.TextField(max_length=45)),
                ('post_nom', models.TextField(max_length=45)),
                ('pre_nom', models.TextField(max_length=45)),
            ],
            options={
                'verbose_name': 'agent',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PresencesAg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.DateField(default=django.utils.timezone.now)),
                ('arrivee', models.BooleanField(default=False)),
                ('depart', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Agent')),
            ],
            options={
                'verbose_name': 'presencesAg',
                'ordering': ['jour'],
            },
        ),
    ]
